language: node_js
node_js: "14"
sudo: false
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - npm run test:core
cache:
  bundler: true
  directories:
    - node_modules
